"""aegis.report_builders — Compliance report Markdown builders.

Extracted from report.py. Three report frameworks:
  - EU AI Act Article 12
  - ISO/IEC 42001
  - AIUC-1 (Insurance Underwriting)

Each builder takes (canister_id, generated_at, summary, stats, health) and
returns a Markdown string.
"""

from __future__ import annotations

from typing import Any

from aegis import __version__
from aegis.report import ReportFormat, ReportSummary

SDK_VERSION = __version__


def _pass_fail(condition: bool) -> str:
    return "[PASS]" if condition else "[FAIL]"


# ---------------------------------------------------------------------------
# Shared report building blocks
# ---------------------------------------------------------------------------


def _report_header(
    title: str,
    canister_id: str,
    generated_at: str,
    summary: ReportSummary,
    extra_lines: list[str] | None = None,
) -> list[str]:
    """Build the common Markdown header."""
    lines = [
        f"# {title}",
        "",
        f"**Canister:** {canister_id}  ",
        f"**Generated:** {generated_at}  ",
        f"**Coverage:** {summary.coverage_start} -- {summary.coverage_end}",
    ]
    if extra_lines:
        for el in extra_lines:
            lines.append(el)
    lines.extend(["", "---", ""])
    return lines


def _compliance_score_section(
    summary: ReportSummary,
    stats: dict[str, Any],
    rows: list[tuple[str, bool]],
    section_title: str = "Compliance Score",
) -> list[str]:
    """Build the common score table and footer."""
    score_pct = int(summary.compliance_score * 100)
    latest_hash = stats.get("latest_chain_hash", "N/A")
    lines = [
        "---",
        "",
        f"## {section_title}: {score_pct}%",
        "",
        "| Criterion | Status |",
        "|-----------|--------|",
    ]
    for label, condition in rows:
        lines.append(f"| {label} | {_pass_fail(condition)} |")
    lines.extend([
        "",
        f"Chain hash at report time: `{latest_hash}`",
        "",
        "*Report generated by aegis-ledger-sdk compliance report generator.*",
        "",
    ])
    return lines


# ---------------------------------------------------------------------------
# Report builders
# ---------------------------------------------------------------------------


def _build_eu_ai_act_report(
    canister_id: str,
    generated_at: str,
    summary: ReportSummary,
    stats: dict[str, Any],
    health: dict[str, Any],
) -> str:
    """Build EU AI Act Article 12 compliance report in Markdown."""
    chain_length = stats.get("chain_length", summary.total_actions)
    latest_hash = stats.get("latest_chain_hash", "N/A")
    active_keys = stats.get("active_api_keys", 0)
    revoked_keys = stats.get("revoked_api_keys", 0)
    uptime = health.get("uptime_seconds", 0)
    status_text = health.get("status", "unknown")

    chain_status = "VERIFIED" if summary.chain_intact else "BROKEN"

    has_actions = summary.total_actions > 0
    has_agents = summary.total_agents > 0

    lines = _report_header(
        "EU AI Act Article 12 -- Logging Compliance Report",
        canister_id, generated_at, summary,
    )
    lines.extend(["## Executive Summary", ""])

    if summary.compliance_score > 0.8:
        lines.append(
            f"The AI system logged on canister `{canister_id}` demonstrates **strong "
            f"compliance** with EU AI Act Article 12 logging requirements. A total of "
            f"{summary.total_actions:,} actions have been recorded across "
            f"{summary.total_agents} agent(s) and {summary.total_sessions} session(s). "
            f"The cryptographic hash chain is {chain_status}, providing full traceability "
            f"of all AI system decisions and operations."
        )
    elif summary.compliance_score >= 0.4:
        lines.append(
            f"The AI system logged on canister `{canister_id}` demonstrates **partial "
            f"compliance** with EU AI Act Article 12. Some logging requirements are met, "
            f"but gaps exist that should be addressed. {summary.total_actions:,} actions "
            f"recorded. Chain integrity: {chain_status}."
        )
    else:
        lines.append(
            f"The AI system logged on canister `{canister_id}` shows **insufficient "
            f"compliance** with EU AI Act Article 12. Critical logging gaps have been "
            f"identified. Immediate remediation is recommended."
        )

    lines.extend([
        "",
        "## 1. Automatic Logging (Art. 12.1)",
        "",
        f"- Total logged actions: {summary.total_actions:,}",
        "- Action types covered: tool_call, decision, observation, error, human_override",
        f"- Logging framework: aegis-ledger-sdk v{SDK_VERSION}",
        f"- Canister health: {status_text}",
        f"- {_pass_fail(has_actions)} Automatic logging is active",
        "",
        "## 2. Traceability (Art. 12.2)",
        "",
        f"- Hash chain length: {chain_length:,}",
        f"- Chain integrity: {chain_status}",
        "- Hash algorithm: SHA-256 (canonical JSON serialization)",
        "- Digital signatures: Ed25519 / ML-DSA-65 / SLH-DSA-128s"
        " / Hybrid (per-entry payload signing)",
        f"- Latest chain hash: `{latest_hash}`",
        f"- {_pass_fail(summary.chain_intact)} Full traceability maintained",
        "",
        "## 3. Monitoring (Art. 12.3)",
        "",
        f"- Active agents: {summary.total_agents}",
        f"- Active sessions: {summary.total_sessions}",
        f"- API keys: {active_keys} active / {revoked_keys} revoked",
        f"- Canister uptime: {uptime:,} seconds",
        f"- {_pass_fail(has_agents)} Monitoring capability confirmed",
        "",
        "## 4. Record Keeping (Art. 12.4)",
        "",
        "- Storage: Internet Computer Protocol (append-only canister)",
        f"- Canister ID: `{canister_id}`",
        "- Retention: Permanent (ICP canister-based, no TTL)",
        "- Access control: Principal-based authentication (Internet Identity)",
        "- Data integrity: Hash-chained entries with Ed25519 signatures",
        f"- {_pass_fail(has_actions)} Records maintained per requirements",
        "",
        "",
        "## Appendix A: Verification Method",
        "",
        "Each ledger entry is cryptographically linked to its predecessor via SHA-256 "
        "hash chaining. The entry's payload is signed with Ed25519 using agent-specific "
        "private keys. Verification can be performed independently using:",
        "",
        "```bash",
        f"aegis verify {canister_id} <action_id>",
        "```",
        "",
        f"Chain length at time of report: **{chain_length:,}** entries.  ",
        f"Latest chain hash: `{latest_hash}`",
        "",
    ])

    lines.extend(_compliance_score_section(summary, stats, [
        ("Automatic Logging", has_actions),
        ("Chain Integrity", summary.chain_intact),
        ("Agent Monitoring", has_agents),
        ("Session Tracking", summary.total_sessions > 0),
        ("API Key Management", active_keys > 0),
    ]))

    return "\n".join(lines)


def _build_iso_42001_report(
    canister_id: str,
    generated_at: str,
    summary: ReportSummary,
    stats: dict[str, Any],
    health: dict[str, Any],
) -> str:
    """Build ISO 42001 AI Management System compliance report in Markdown."""
    chain_length = stats.get("chain_length", summary.total_actions)
    active_keys = stats.get("active_api_keys", 0)
    revoked_keys = stats.get("revoked_api_keys", 0)
    status_text = health.get("status", "unknown")

    has_actions = summary.total_actions > 0
    has_agents = summary.total_agents > 0

    lines = _report_header(
        "ISO/IEC 42001 -- AI Management System Compliance Report",
        canister_id, generated_at, summary,
        extra_lines=["**Standard:** ISO/IEC 42001:2023 Artificial Intelligence Management System"],
    )
    lines.extend([
        "## Executive Summary",
        "",
        f"This report documents the AI system logging controls implemented via the Aegis "
        f"Ledger on canister `{canister_id}`. The assessment covers control objectives "
        f"A.6.2.6 (AI System Logging), A.8.4 (Documentation of AI System Operation), and "
        f"A.9.3 (AI Monitoring and Measurement) as defined in ISO/IEC 42001:2023 Annex A.",
        "",
        "## A.6.2.6 -- AI System Logging",
        "",
        "**Objective:** The organization shall implement logging mechanisms for AI systems "
        "to enable monitoring, auditing, and incident investigation.",
        "",
        "| Control | Evidence | Status |",
        "|---------|----------|--------|",
        f"| Event logging enabled | {summary.total_actions:,} actions recorded | "
        f"{_pass_fail(has_actions)} |",
        f"| Log integrity protection | SHA-256 hash chain ({chain_length:,} entries) | "
        f"{_pass_fail(summary.chain_intact)} |",
        f"| Digital signatures | Ed25519 / ML-DSA-65 / SLH-DSA-128s / Hybrid (per-entry) | "
        f"{_pass_fail(has_actions)} |",
        f"| Tamper detection | Append-only hash-chained storage (ICP) | "
        f"{_pass_fail(summary.chain_intact)} |",
        "| Log retention | Permanent (no TTL, canister-based) | [PASS] |",
        "",
        "### Logging Coverage",
        "",
        "- Action types: tool_call, decision, observation, error, human_override",
        "- Captured fields: agent_id, session_id, sequence_number, timestamps, "
        "input/output hashes, duration, status, decision reasoning, confidence scores",
        f"- Framework: aegis-ledger-sdk v{SDK_VERSION}",
        f"- System health: {status_text}",
        "",
        "## A.8.4 -- Documentation of AI System Operation",
        "",
        "**Objective:** The organization shall maintain documentation of AI system "
        "operations sufficient for review and audit.",
        "",
        "| Control | Evidence | Status |",
        "|---------|----------|--------|",
        f"| Operational records | {summary.total_actions:,} logged operations | "
        f"{_pass_fail(has_actions)} |",
        f"| Agent identification | {summary.total_agents} registered agent(s) | "
        f"{_pass_fail(has_agents)} |",
        f"| Session tracking | {summary.total_sessions} session(s) recorded | "
        f"{_pass_fail(summary.total_sessions > 0)} |",
        f"| Access management | {active_keys} active / {revoked_keys} revoked API keys | "
        f"{_pass_fail(active_keys > 0)} |",
        f"| Causal tracing | Parent action IDs + decision reasoning fields | "
        f"{_pass_fail(has_actions)} |",
        "",
        "## A.9.3 -- AI Monitoring and Measurement",
        "",
        "**Objective:** The organization shall monitor and measure AI system performance "
        "and behavior.",
        "",
        "| Control | Evidence | Status |",
        "|---------|----------|--------|",
        f"| Real-time monitoring | Canister health endpoint (status: {status_text}) | "
        f"{_pass_fail(status_text == 'healthy')} |",
        f"| Chain verification | On-demand entry verification via CLI/API | "
        f"{_pass_fail(summary.chain_intact)} |",
        f"| Anomaly detection | Duration tracking, error action logging | "
        f"{_pass_fail(has_actions)} |",
        f"| Audit trail | Hash-chained append-only ledger | "
        f"{_pass_fail(summary.chain_intact)} |",
        "",
    ])

    lines.extend(_compliance_score_section(summary, stats, [
        ("A.6.2.6 AI System Logging", has_actions and summary.chain_intact),
        ("A.8.4 Documentation", has_actions and has_agents),
        ("A.9.3 Monitoring", status_text == "healthy"),
    ], section_title="Overall Compliance Score"))

    return "\n".join(lines)


def _build_aiuc_1_report(
    canister_id: str,
    generated_at: str,
    summary: ReportSummary,
    stats: dict[str, Any],
    health: dict[str, Any],
) -> str:
    """Build AIUC-1 insurance underwriting compliance report in Markdown."""
    chain_length = stats.get("chain_length", summary.total_actions)
    latest_hash = stats.get("latest_chain_hash", "N/A")
    active_keys = stats.get("active_api_keys", 0)
    status_text = health.get("status", "unknown")
    uptime = health.get("uptime_seconds", 0)

    has_actions = summary.total_actions > 0

    lines = _report_header(
        "AIUC-1 -- AI Underwriting Compliance Report",
        canister_id, generated_at, summary,
        extra_lines=["**Framework:** AIUC-1 (AI Underwriting Criteria for Insurance)"],
    )
    lines.extend([
        "## Executive Summary",
        "",
        f"This report provides evidence of continuous AI system logging, chain integrity, "
        f"and incident detection capability for insurance underwriting assessment. The Aegis "
        f"Ledger on canister `{canister_id}` serves as the tamper-evident audit trail for all "
        f"AI agent operations.",
        "",
        "## 1. Evidence of Continuous Logging",
        "",
        "Continuous, uninterrupted logging is required to demonstrate that all AI system "
        "actions are captured without gaps.",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total actions logged | {summary.total_actions:,} |",
        f"| Agents monitored | {summary.total_agents} |",
        f"| Sessions tracked | {summary.total_sessions} |",
        f"| Coverage period | {summary.coverage_start} to {summary.coverage_end} |",
        f"| Logging framework | aegis-ledger-sdk v{SDK_VERSION} |",
        f"| API keys active | {active_keys} |",
        "",
        f"**Assessment:** {_pass_fail(has_actions)} Continuous logging "
        f"{'is' if has_actions else 'is NOT'} evidenced.",
        "",
        "## 2. Chain Integrity Proof",
        "",
        "Tamper evidence is demonstrated through cryptographic hash chaining and "
        "digital signatures on an append-only ledger.",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Hash chain length | {chain_length:,} |",
        f"| Chain integrity | {'INTACT' if summary.chain_intact else 'COMPROMISED'} |",
        "| Hash algorithm | SHA-256 (canonical JSON) |",
        "| Signature scheme | Ed25519 / ML-DSA-65 / SLH-DSA-128s / Hybrid (per-entry) |",
        "| Storage backend | Internet Computer Protocol (ICP) |",
        f"| Latest chain hash | `{latest_hash}` |",
        "",
        f"**Assessment:** {_pass_fail(summary.chain_intact)} Chain integrity "
        f"{'is' if summary.chain_intact else 'is NOT'} verified.",
        "",
        "## 3. Incident Detection Capability",
        "",
        "The system must demonstrate the ability to detect and record anomalous "
        "AI behavior, including errors, timeouts, and unexpected decisions.",
        "",
        "| Capability | Implementation |",
        "|------------|----------------|",
        "| Error logging | Dedicated `error` action type with stack traces |",
        "| Timeout detection | `timeout` status recorded with duration_ms |",
        "| Decision reasoning | `decision_reasoning` field per action |",
        "| Confidence tracking | `confidence_score` (0.0-1.0) per action |",
        "| Human override logging | Dedicated `human_override` action type |",
        "| Real-time health | Canister health endpoint |",
        "",
        f"**Assessment:** {_pass_fail(has_actions)} Incident detection capability "
        f"{'is' if has_actions else 'is NOT'} confirmed.",
        "",
        "## 4. Data Retention Proof",
        "",
        "Insurance underwriting requires proof that audit data is tamper-evident "
        "and cryptographically verifiable.",
        "",
        "| Property | Evidence |",
        "|----------|----------|",
        f"| Tamper evidence | ICP canister-based storage (canister `{canister_id}`) |",
        "| Retention period | Permanent (no expiration, no TTL) |",
        "| Geographic distribution | ICP subnet nodes (distributed) |",
        "| Access control | Principal-based authentication |",
        "| Backup mechanism | Hash chain enables independent verification |",
        f"| System uptime | {uptime:,} seconds since last restart |",
        f"| System status | {status_text} |",
        "",
        f"**Assessment:** {_pass_fail(summary.chain_intact)} Data retention requirements "
        f"{'are' if summary.chain_intact else 'are NOT'} met.",
        "",
    ])

    lines.extend(_compliance_score_section(summary, stats, [
        ("Continuous Logging", has_actions),
        ("Chain Integrity", summary.chain_intact),
        ("Incident Detection", has_actions),
        ("Data Retention", summary.chain_intact),
    ], section_title="Risk Assessment Score"))

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Format dispatcher
# ---------------------------------------------------------------------------

BUILDERS: dict[ReportFormat, Any] = {
    ReportFormat.EU_AI_ACT: _build_eu_ai_act_report,
    ReportFormat.ISO_42001: _build_iso_42001_report,
    ReportFormat.AIUC_1: _build_aiuc_1_report,
}
